Repository kebblar/petstore-back, pull requests merged in 2021-06, with the labels that each got.

#209 Update db
  src/test/resources/extra/db/db.sql
Labels: Vimpollos

#210 Fix/administracion compras
  src/main/java/io/kebblar/petstore/api/mapper/AdministracionComprasMapper.java
  src/main/java/io/kebblar/petstore/api/mapper/HistorialComprasMapper.java
  src/main/java/io/kebblar/petstore/api/model/domain/AdministracionCompras.java
  src/main/java/io/kebblar/petstore/api/model/domain/HistorialCompras.java
  src/main/java/io/kebblar/petstore/api/rest/AdministracionComprasController.java
  src/main/java/io/kebblar/petstore/api/rest/HistorialComprasController.java
  src/main/java/io/kebblar/petstore/api/service/AdministracionComprasService.java
  src/main/java/io/kebblar/petstore/api/service/AdministracionComprasServiceImpl.java
  src/main/java/io/kebblar/petstore/api/service/HistorialComprasService.java
  src/main/java/io/kebblar/petstore/api/service/HistorialComprasServiceImpl.java
  src/test/java/io/kebblar/petstore/api/service/TestAdministracionComprasService.java
  src/test/java/io/kebblar/petstore/api/service/TestHistorialComprasService.java
Labels: Vimpollos

#228 Crud de los catalogos de municipio estado pais
  src/main/java/io/kebblar/petstore/api/mapper/EstadoMapper.java
  src/main/java/io/kebblar/petstore/api/mapper/MunicipioMapper.java
  src/main/java/io/kebblar/petstore/api/mapper/PaisMapper.java
  src/main/java/io/kebblar/petstore/api/model/domain/Estado.java
  src/main/java/io/kebblar/petstore/api/model/domain/Municipio.java
  src/main/java/io/kebblar/petstore/api/rest/EstadoController.java
  src/main/java/io/kebblar/petstore/api/rest/MunicipioController.java
  src/main/java/io/kebblar/petstore/api/rest/PaisController.java
  src/main/java/io/kebblar/petstore/api/service/EstadoService.java
  src/main/java/io/kebblar/petstore/api/service/EstadoServiceImpl.java
  src/main/java/io/kebblar/petstore/api/service/MunicipioService.java
  src/main/java/io/kebblar/petstore/api/service/MunicipioServiceImpl.java
  src/main/java/io/kebblar/petstore/api/service/PaisService.java
  src/main/java/io/kebblar/petstore/api/service/PaisServiceImpl.java
Labels: Coding love, bug

#248 Se corrige bug de busqueda administrativa de anuncios
  src/main/java/io/kebblar/petstore/api/model/response/BusquedaAdministracionResponse.java
Labels: Equipo azul

#255 Fix/mejoras producto
  src/main/java/io/kebblar/petstore/api/mapper/AnuncioMapper.java
  src/main/java/io/kebblar/petstore/api/service/AnuncioService.java
  src/main/java/io/kebblar/petstore/api/service/AnuncioServiceImpl.java
  src/main/java/io/kebblar/petstore/api/utils/AnuncioUtil.java
  src/main/resources/application.properties
Labels: Equipo azul

#266 Integración pruebas unitarias y mejoras
  src/main/java/io/kebblar/petstore/api/service/AnuncioServiceImpl.java
  src/main/java/io/kebblar/petstore/api/utils/AnuncioUtil.java
  src/test/java/io/kebblar/petstore/api/service/TestAnuncioService.java
Labels: Equipo azul

#276 Bug en el manejo de fechas
  pom.xml
  src/main/java/io/kebblar/petstore/api/model/domain/Anuncio.java
  src/main/java/io/kebblar/petstore/api/model/response/DetalleAnuncioResponse.java
  src/main/java/io/kebblar/petstore/api/service/AnuncioServiceImpl.java
  src/main/java/io/kebblar/petstore/api/utils/AnuncioUtil.java
  src/test/java/io/kebblar/petstore/api/service/TestAnuncioService.java
Labels: Equipo azul, bug

#290 Feature/url search
  src/main/java/io/kebblar/petstore/api/mapper/AnuncioMapper.java
  src/main/java/io/kebblar/petstore/api/model/domain/Anuncio.java
  src/main/java/io/kebblar/petstore/api/model/domain/ChartData.java
  src/main/java/io/kebblar/petstore/api/model/exceptions/NotFoundException.java
  src/main/java/io/kebblar/petstore/api/rest/AdminController.java
  src/main/java/io/kebblar/petstore/api/rest/AnuncioController.java
  src/main/java/io/kebblar/petstore/api/service/AnuncioService.java
  src/main/java/io/kebblar/petstore/api/service/AnuncioServiceImpl.java
  src/test/java/io/kebblar/petstore/api/service/TestAnuncioService.java
  src/test/java/io/kebblar/petstore/api/utils/LimpiaTest.java
  src/test/java/io/kebblar/petstore/api/utils/TestSignFile.java
  src/test/resources/extra/db/db.sql
Labels: enhancement
